### ISSUE TITLE
Request: Not use italic font for GitHub Copilot suggestions?

### ISSUE THREAD

**Issue by raffertyuy** [idbartosz/vscode-darkpp-italic#8]
Hi, thank you for this excellent theme. I am using GitHub copilot and unfortunately the code suggestions are using the cursive/italic font. Can this be modified so that the suggestions are not cursive?

**Comment by idbartosz** [comment]
I missed the notification, a suggestion to resolve this issue has been added to the README.md file.

Sorry for keeping you waiting for so long, I hope that you still enjoy this theme!

```css
/**
* VSCode will warn you that this change indicates a corrupt installation - click the gear icon and ignore it
* NOTE: whenever you make changes to this file, you must close all VSCode instances to see the changes
*/

/* Enhance italic fonts styling */
.mtki {
    font-size: 1em; /* use 1.25em to increase italic tokens size, 1.25em might look better on Windows machines */
    font-stretch: ultra-condensed;
}


/* BEGIN: Enhance Copilot suggestions styling */
span.mtk1.ghost-text-decoration, span.mtk1.ghost-text {
  color: #B0B0B0 !important;
  font-style: normal !important;
}

:nth-last-child(1 of span.mtk1.ghost-text-decoration)::after {
  content: ' {Copilot}';
  color: #FF69B4;
  font-style: italic;
}
/* END: Enhance Copilot suggestions styling */

/*!--------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
...
```
